AGENTS:
  - NAME: agent_1
    TYPE: HOLONOMIC
    STARTING_POSE: [150, 150, 0]
    STARTING_VELOCITY: [5, 0, 0]
  - NAME: agent_2
    TYPE: HOLONOMIC
    STARTING_POSE: [220, 150, 3.14]
    STARTING_VELOCITY: [0, 5, 0]
