AGENTS:
  - NAME: agent_1
    TYPE: HOLONOMIC
    STARTING_POSE: [150, 150, 0]
    STARTING_VELOCITY: [0, 0, 0]
    MAX_VELOCITY: [10, 10, 1]
  - NAME: agent_2
    TYPE: HOLONOMIC
    STARTING_POSE: [220, 150, 3.14]
    GOAL_POSE: [220, 300, 0]
    STARTING_VELOCITY: [0, 0, 0]
    MAX_VELOCITY: [10, 10, 1]
