AGENTS:
  - NAME: agent_1
    TYPE: HOLONOMIC
    STARTING_POSE: [350, 500, 0]
    GOAL_POSE: [65, 575, 0]
    STARTING_VELOCITY: [0, 0, 0]
  - NAME: agent_2
    TYPE: HOLONOMIC
    STARTING_POSE: [300, 600, 3.14]
    GOAL_POSE: [120, 250, 0]
    STARTING_VELOCITY: [0, 0, 0]
  - NAME: agent_3
    TYPE: HOLONOMIC
    STARTING_POSE: [350, 670, 3.14]
    GOAL_POSE: [150, 250, 0]
    STARTING_VELOCITY: [0, 0, 0]
